var songs = [
    {"title": "A Little Respect", "artist": "Erasure", "page": 7},
    {"title": "A Whole New World (Aladdin)", "artist": "Menken and Rice", "page": 8},
    {"title": "Accidentally in Love", "artist": "Counting Crows", "page": 9},
    {"title": "Ain't No Sunshine", "artist": "Bill Withers", "page": 10},
    {"title": "All My Loving", "artist": "The Beatles", "page": 11},
    {"title": "All That She Wants", "artist": "Ace of Base", "page": 12},
    {"title": "Alright", "artist": "Supergrass", "page": 13},
    {"title": "Always Look On The Bright Side Of Life", "artist": "Monty Python", "page": 14},
    {"title": "(Is this the Way to) Amarillo", "artist": "Tony Christie", "page": 15},
    {"title": "Angels", "artist": "Robbie Williams", "page": 16},
    {"title": "Annie's Song", "artist": "John Denver", "page": 17},
    {"title": "Anyone Else But You", "artist": "The Moldy Peaches (abridged) ", "page": 18},
    {"title": "Back for Good", "artist": "Take That", "page": 19},
    {"title": "Back in the USSR", "artist": "The Beatles", "page": 20},
    {"title": "Bad Moon Rising", "artist": "Creedence Clearwater Revival", "page": 21},
    {"title": "Baker Street", "artist": "Gerry Rafferty", "page": 22},
    {"title": "The Bare Necessities", "artist": "Terry Gilkyson", "page": 23},
    {"title": "Be My Baby", "artist": "The Ronettes", "page": 24},
    {"title": "Bed of Roses", "artist": "Bon Jovi", "page": 25},
    {"title": "Big Yellow Taxi", "artist": "Joni Mitchell", "page": 26},
    {"title": "Blitzkrieg Bop", "artist": "The Ramones", "page": 27},
    {"title": "Blame it on the Boogie", "artist": "The Jacksons", "page": 28},
    {"title": "Blaze of Glory", "artist": "Jon Bon Jovi", "page": 29},
    {"title": "Blowin' in the Wind", "artist": "Bob Dylan", "page": 30},
    {"title": "Blue Moon", "artist": "Rogers and Hart", "page": 31},
    {"title": "Blue Suede Shoes", "artist": "Elvis Presley", "page": 32},
    {"title": "Bohemian Like You", "artist": "Dandy Warhols", "page": 33},
    {"title": "Born to be Wild", "artist": "Steppenwolf", "page": 34},
    {"title": "Boulevard of Broken Dreams", "artist": "Green Day", "page": 35},
    {"title": "Breakfast at Tiffany's", "artist": "Deep Blue Something", "page": 36},
    {"title": "Brimful of Asha", "artist": "Cornershop", "page": 37},
    {"title": "Bring Me Sunshine", "artist": "Morecambe & Wise", "page": 38},
    {"title": "Brown-Eyed Girl", "artist": "Van Morrison", "page": 39},
    {"title": "Build Me Up Buttercup", "artist": "The Foundations", "page": 40},
    {"title": "California Dreaming", "artist": "The Mamas and the Papas", "page": 41},
    {"title": "Cannonball", "artist": "Damien Rice", "page": 42},
    {"title": "Can't Take My Eyes Off You", "artist": "Frankie Valli", "page": 43},
    {"title": "Cats in the Cradle", "artist": "Ugly Kid Joe", "page": 44},
    {"title": "Cecilia", "artist": "Simon and Garfunkel", "page": 45},
    {"title": "The Chain", "artist": "Fleetwood Mac", "page": 46},
    {"title": "Chelsea Dagger", "artist": "The Fratellis", "page": 47},
    {"title": "City of New Orleans", "artist": "Arlo Guthrie", "page": 48},
    {"title": "Closing Time", "artist": "Semisonic", "page": 49},
    {"title": "Come on Eileen", "artist": "Dexy's Midnight Runners", "page": 50},
    {"title": "Common People", "artist": "Pulp (short version) ", "page": 51},
    {"title": "Complicated", "artist": "Avril Lavigne", "page": 52},
    {"title": "Country House", "artist": "Blur", "page": 53},
    {"title": "Crazy", "artist": "Gnarls Barkley", "page": 54},
    {"title": "Creep", "artist": "Radiohead", "page": 55},
    {"title": "Crocodile Rock", "artist": "Elton John", "page": 56},
    {"title": "Dancing in the Dark", "artist": "Bruce Springsteen", "page": 57},
    {"title": "Dancing Queen", "artist": "Abba", "page": 58},
    {"title": "Daydream", "artist": "Lovin' Spoonful", "page": 59},
    {"title": "Daydream Believer", "artist": "The Monkees", "page": 60},
    {"title": "Dedicated Follower of Fashion", "artist": "The Kinks", "page": 61},
    {"title": "Delilah", "artist": "Tom Jones", "page": 62},
    {"title": "Dirty Old Town", "artist": "The Pogues", "page": 63},
    {"title": "Disco 2000", "artist": "Pulp", "page": 64},
    {"title": "Do You Love Me", "artist": "The Contours", "page": 65},
    {"title": "Don't Leave Me This Way", "artist": "Thelma Houston", "page": 66},
    {"title": "Don't Stop Believin'", "artist": "Journey", "page": 67},
    {"title": "Don't Stop Me Now", "artist": "Queen", "page": 68},
    {"title": "Don't Look Back in Anger", "artist": "Oasis", "page": 69},
    {"title": "Don't You Want Me", "artist": "Human League", "page": 70},
    {"title": "Don't Worry, Be Happy", "artist": "Bobby McFerrin", "page": 71},
    {"title": "Down Under", "artist": "Men at Work", "page": 72},
    {"title": "Dream a Little Dream of Me", "artist": "The Mamas & The Papas", "page": 73},
    {"title": "Ever Fallen in Love", "artist": "Buzzcocks", "page": 74},
    {"title": "Every Breath You Take", "artist": "The Police", "page": 75},
    {"title": "Everything I Do", "artist": "Bryan Adams", "page": 76},
    {"title": "Eye of the Tiger", "artist": "Survivor", "page": 77},
    {"title": "Faith", "artist": "George Michael", "page": 78},
    {"title": "The Final Countdown", "artist": "Europe", "page": 79},
    {"title": "Finally", "artist": "CeCe Peniston", "page": 80},
    {"title": "Fifty ways to leave your lover", "artist": "Paul Simon", "page": 81},
    {"title": "Five Foot Two, Eyes of Blue", "artist": "Lewis, Young & Henderson", "page": 82},
    {"title": "Five Hundred Miles", "artist": "The Proclaimers", "page": 83},
    {"title": "Folsom Prison Blues", "artist": "Johnny Cash", "page": 84},
    {"title": "Forget You/Fk You", "artist": "Cee Lo Green", "page": 85},
    {"title": "Free Bird", "artist": "Lynyrd Skynyrd", "page": 86},
    {"title": "Friday I'm In Love", "artist": "The Cure", "page": 87},
    {"title": "Get Lucky (abridged)", "artist": "Daft Punk", "page": 88},
    {"title": "Go Your Own Way", "artist": "Fleetwood Mac", "page": 89},
    {"title": "Gold", "artist": "Spandau Ballet", "page": 90},
    {"title": "Good Riddance (Time of Your Life)", "artist": "Green Day", "page": 91},
    {"title": "Half the World Away", "artist": "Oasis", "page": 92},
    {"title": "Hallelujah (abridged)", "artist": "Leonard Cohen", "page": 93},
    {"title": "Hand In My Pocket", "artist": "Alanis Morissette", "page": 94},
    {"title": "Happy Birthday (traditional)", "page": 95},
    {"title": "Happy Together", "artist": "The Turtles", "page": 96},
    {"title": "Have You Ever Seen the Rain?", "artist": "Creedence Clearwater Revival", "page": 97},
    {"title": "Heaven", "artist": "Bryan Adams", "page": 98},
    {"title": "Hello", "artist": "Adele Adkins and Greg Kurstin", "page": 99},
    {"title": "\"Heroes\"", "artist": "David Bowie", "page": 100},
    {"title": "Hey Jude", "artist": "The Beatles", "page": 101},
    {"title": "Hey Ya (abridged)", "artist": "OutKast", "page": 102},
    {"title": "Hi Ho Silver Lining", "artist": "Jeff Beck", "page": 103},
    {"title": "Hit Me Baby One More Time", "artist": "Britney Spears", "page": 104},
    {"title": "Hit the Road", "artist": "Ray Charles", "page": 105},
    {"title": "Ho Hey", "artist": "The Lumineers", "page": 106},
    {"title": "Hot n Cold", "artist": "Katy Perry", "page": 107},
    {"title": "Hotel California", "artist": "The Eagles", "page": 108},
    {"title": "House of the Rising Sun (abridged)", "artist": "The Animals", "page": 109},
    {"title": "Hurt", "artist": "Johnny Cash", "page": 110},
    {"title": "I Can See Clearly Now", "artist": "Johnny Nash", "page": 111},
    {"title": "I Knew You Were Trouble", "artist": "Taylor Swift", "page": 112},
    {"title": "I Only Want to Be With You", "artist": "Dusty Springfield", "page": 113},
    {"title": "I Predict a Riot", "artist": "Kaiser Chiefs", "page": 114},
    {"title": "I Saw Her Standing There", "artist": "The Beatles", "page": 115},
    {"title": "I Think We're Alone Now", "artist": "Tiffany", "page": 116},
    {"title": "I Wanna Be Like You", "artist": "R.M. Sherman and R.B. Sherman", "page": 117},
    {"title": "I Want to Break Free", "artist": "Queen", "page": 118},
    {"title": "I Want to Know What Love Is", "artist": "Foreigner", "page": 119},
    {"title": "I Will Survive", "artist": "Gloria Gaynor", "page": 120},
    {"title": "I'll Be There For You (Friends theme tune)", "artist": "The Rembrandts", "page": 121},
    {"title": "I'll Be Your Baby", "artist": "Bob Dylan", "page": 122},
    {"title": "I'll Fly Away", "artist": "Alison Krauss et al", "page": 123},
    {"title": "I'm a Believer", "artist": "The Monkees", "page": 124},
    {"title": "I'm into Something Good", "artist": "Herman's Hermits", "page": 125},
    {"title": "I'm Yours", "artist": "Jason Mraz", "page": 126},
    {"title": "If it Makes You Happy", "artist": "Sheryl Crowe", "page": 127},
    {"title": "Iko Iko", "artist": "\"Jockamo\" James Crawford", "page": 128},
    {"title": "Imagine", "artist": "John Lennon", "page": 129},
    {"title": "In the Summertime", "artist": "Mungo Jerry", "page": 130},
    {"title": "Iris", "artist": "The Goo Goo Dolls", "page": 131},
    {"title": "It Must Be Love", "artist": "Madness", "page": 132},
    {"title": "It's Not Unusual", "artist": "Tom Jones", "page": 133},
    {"title": "Jammin'", "artist": "Bob Marley", "page": 134},
    {"title": "The Joker", "artist": "Steve Miller Band", "page": 135},
    {"title": "Johnny B. Goode", "artist": "Chuck Berry", "page": 136},
    {"title": "Jolene", "artist": "Dolly Parton", "page": 137},
    {"title": "Karma Chameleon", "artist": "Culture Club", "page": 138},
    {"title": "Keep the Faith", "artist": "Bon Jovi", "page": 139},
    {"title": "Kids", "artist": "MGMT", "page": 140},
    {"title": "Kids in America", "artist": "Kim Wilde", "page": 141},
    {"title": "Killing Me Softly", "artist": "Roberta Flack/The Fugees", "page": 142},
    {"title": "King of the Road", "artist": "Roger Miller", "page": 143},
    {"title": "Kiss Me", "artist": "Sixpence None the Richer", "page": 144},
    {"title": "Knockin' On Heaven's Door", "artist": "Bob Dylan", "page": 145},
    {"title": "Lady Madonna", "artist": "The Beatles", "page": 146},
    {"title": "Let it Be", "artist": "The Beatles", "page": 147},
    {"title": "Let it Go", "artist": "Frozen", "page": 148},
    {"title": "Like a Prayer", "artist": "Madonna", "page": 149},
    {"title": "The Lion Sleeps Tonight", "artist": "The Tokens", "page": 150},
    {"title": "Little Lion Man", "artist": "Mumford and Sons", "page": 151},
    {"title": "Live Forever", "artist": "Oasis", "page": 152},
    {"title": "Livin' On A Prayer", "artist": "Bon Jovi", "page": 153},
    {"title": "The Loco-motion", "artist": "Little Eva", "page": 154},
    {"title": "Lola", "artist": "The Kinks", "page": 155},
    {"title": "Losing My Religion", "artist": "REM", "page": 156},
    {"title": "Lucky Man", "artist": "The Verve", "page": 157},
    {"title": "Mad World", "artist": "Gary Jules", "page": 158},
    {"title": "Maggie May", "artist": "Rod Stewart", "page": 159},
    {"title": "Make Me Smile (Come Up and See Me)", "artist": "Steve Harley", "page": 160},
    {"title": "Man of Constant Sorrow", "artist": "The Soggy Bottom Boys", "page": 161},
    {"title": "Maybe Tomorrow", "artist": "Terry Bush (Littlest Hobo theme)", "page": 162},
    {"title": "Me and Julio Down by the Schoolyard", "artist": "Paul Simon", "page": 163},
    {"title": "Monkey Man", "artist": "Toots and the Maytals", "page": 164},
    {"title": "Moondance", "artist": "Van Morrison", "page": 165},
    {"title": "Mrs Robinson", "artist": "Simon & Garfunkel", "page": 166},
    {"title": "My Favourite Game", "artist": "The Cardigans", "page": 167},
    {"title": "New York, New York", "artist": "Frank Sinatra", "page": 168},
    {"title": "Nine to Five", "artist": "Dolly Parton", "page": 169},
    {"title": "No Surprises", "artist": "Radiohead", "page": 170},
    {"title": "No Woman, No Cry", "artist": "Bob Marley & The Wailers", "page": 171},
    {"title": "Ob-La-Di, Ob-La-Da", "artist": "The Beatles", "page": 172},
    {"title": "Octopus's Garden", "artist": "The Beatles", "page": 173},
    {"title": "Ordinary World", "artist": "Duran Duran", "page": 174},
    {"title": "Otherside", "artist": "Red Hot Chili Peppers", "page": 175},
    {"title": "(Lookin' Back) Over My Shoulder", "artist": "Mike & the Mechanics", "page": 176},
    {"title": "Paint it Black", "artist": "The Rolling Stones", "page": 177},
    {"title": "People Are Strange", "artist": "The Doors", "page": 178},
    {"title": "Perfect Day", "artist": "Lou Reed", "page": 179},
    {"title": "Piece of my Heart", "artist": "Erma Franklin", "page": 180},
    {"title": "Pinball Wizard", "artist": "The Who", "page": 181},
    {"title": "Poison", "artist": "Alice Cooper", "page": 182},
    {"title": "Pretty Woman", "artist": "Roy Orbison", "page": 183},
    {"title": "Price Tag", "artist": "Jessie J", "page": 184},
    {"title": "Psycho Killer", "artist": "Talking Heads", "page": 185},
    {"title": "Pumped Up Kicks", "artist": "Foster and the People", "page": 186},
    {"title": "Que Sera Sera", "artist": "Doris Day", "page": 187},
    {"title": "Raindrops Keep Fallin on my Head", "artist": "Burt Bacharach", "page": 188},
    {"title": "Ring of Fire", "artist": "Johnny Cash", "page": 189},
    {"title": "Riptide", "artist": "Vance Joy", "page": 190},
    {"title": "Rolling in the Deep", "artist": "Adele", "page": 191},
    {"title": "Run for Your Life", "artist": "The Beatles", "page": 192},
    {"title": "Runaway", "artist": "Del Shannon", "page": 193},
    {"title": "Save Tonight", "artist": "Eagle Eye Cherry", "page": 194},
    {"title": "Shake it Off", "artist": "Taylor Swift", "page": 195},
    {"title": "Should I Stay or Should I Go", "artist": "The Clash", "page": 196},
    {"title": "Sit Down", "artist": "James", "page": 197},
    {"title": "(Sittin' on the) Dock of the Bay", "artist": "Otis Redding", "page": 198},
    {"title": "Skinny Love", "artist": "Bon Iver", "page": 199},
    {"title": "Skyfall", "artist": "Adele", "page": 200},
    {"title": "Sloop John B", "artist": "The Beach Boys", "page": 201},
    {"title": "Somebody That I Used to Know", "artist": "Gotye", "page": 202},
    {"title": "Someone to Lava", "artist": "Pixar", "page": 203},
    {"title": "Something", "artist": "The Beatles", "page": 204},
    {"title": "Somewhere Only We Go", "artist": "Keane", "page": 205},
    {"title": "Somewhere Over the Rainbow", "artist": "Arlen and Harburg", "page": 206},
    {"title": "Somewhere Over the Rainbow / Wonderful World", "artist": "Israel Kamakawiwo'ole", "page": 207},
    {"title": "SOS", "artist": "Abba", "page": 208},
    {"title": "Sound of Silence", "artist": "Simon & Garfunkel", "page": 209},
    {"title": "Space Oddity", "artist": "David Bowie", "page": 210},
    {"title": "Spirit in the Sky", "artist": "Norman Greenbaum", "page": 211},
    {"title": "Stand by Me", "artist": "Ben E King", "page": 212},
    {"title": "Stand By Me", "artist": "Oasis", "page": 213},
    {"title": "Stuck in the Middle with You", "artist": "Stealers Wheel", "page": 214},
    {"title": "Sugar Pie, Honey Bunch", "artist": "The Four Tops", "page": 215},
    {"title": "Summer of 69", "artist": "Bryan Adams", "page": 216},
    {"title": "Sunny Afternoon", "artist": "The Kinks", "page": 217},
    {"title": "Suspicious Minds", "artist": "Elvis Presley", "page": 218},
    {"title": "Sway", "artist": "Dean Martin", "page": 219},
    {"title": "Sweet Child o' Mine", "artist": "Guns 'n' Roses", "page": 220},
    {"title": "Sweet Home Alabama", "artist": "Lynyrd Skynyrd", "page": 221},
    {"title": "Tainted Love", "artist": "Soft Cell", "page": 222},
    {"title": "Take it Easy", "artist": "The Eagles", "page": 223},
    {"title": "Take Me Home, Country Roads", "artist": "John Denver", "page": 224},
    {"title": "Take on Me", "artist": "Aha", "page": 225},
    {"title": "Take Your Mama", "artist": "Scissor Sisters", "page": 226},
    {"title": "Teenage Dirtbag", "artist": "Wheatus", "page": 227},
    {"title": "Teenage Kicks", "artist": "The Undertones", "page": 228},
    {"title": "Tell Me Ma", "artist": "The Dubliners", "page": 229},
    {"title": "The Letter", "artist": "The Boxtops", "page": 230},
    {"title": "The Way It Is", "artist": "Bruce Hornsby", "page": 231},
    {"title": "These Boots Are Made for Walkin'", "artist": "Nancy Sinatra", "page": 232},
    {"title": "Thorn in my Side", "artist": "Eurythmics", "page": 233},
    {"title": "Three Little Birds", "artist": "Bob Marley", "page": 234},
    {"title": "Time After Time", "artist": "Cindy Lauper", "page": 235},
    {"title": "Titanium", "artist": "David Guetta ft. Sia", "page": 236},
    {"title": "Top of the World", "artist": "The Carpenters", "page": 237},
    {"title": "Torn", "artist": "Natalie Imbruglia", "page": 238},
    {"title": "Total Eclipse of the Heart", "artist": "Bonnie Tyler", "page": 239},
    {"title": "Toxic", "artist": "Britney Spears", "page": 240},
    {"title": "True Colours", "artist": "Cindy Lauper", "page": 241},
    {"title": "True Faith", "artist": "New Order", "page": 242},
    {"title": "Tubthumping", "artist": "Chumbawumba", "page": 243},
    {"title": "Two Princes", "artist": "Spin Doctors", "page": 244},
    {"title": "Umbrella", "artist": "Rihanna", "page": 245},
    {"title": "Under The Boardwalk", "artist": "The Drifters", "page": 246},
    {"title": "Under the Bridge", "artist": "Red Hot Chili Peppers", "page": 247},
    {"title": "Valerie / Kung Fu Fighting", "artist": "The Zutons / Carl Douglas", "page": 248},
    {"title": "Video Killed the Radio Star", "artist": "The Buggles", "page": 249},
    {"title": "Walk of Life", "artist": "Dire Straits", "page": 250},
    {"title": "Walking in Memphis", "artist": "Mark Cohn", "page": 251},
    {"title": "Wanted: Dead or Alive", "artist": "Bon Jovi", "page": 252},
    {"title": "We Are Family", "artist": "Sister Sledge", "page": 253},
    {"title": "We Are Young", "artist": "Fun with Janelle Monae", "page": 254},
    {"title": "We Built this City", "artist": "Starship", "page": 255},
    {"title": "Weather With You", "artist": "Crowded House", "page": 256},
    {"title": "What a Wonderful World", "artist": "Sam Cooke", "page": 257},
    {"title": "What's Up", "artist": "4 Non Blondes", "page": 258},
    {"title": "Where do you go to my Lovely? (abridged)", "artist": "Peter Sarstedt", "page": 259},
    {"title": "Why Does it Always Rain on Me?", "artist": "Travis", "page": 260},
    {"title": "Wicked Game", "artist": "Chris Isaak", "page": 261},
    {"title": "Wild World", "artist": "Cat Stevens", "page": 262},
    {"title": "Will You Still Love me Tomorrow?", "artist": "The Shirelles", "page": 263},
    {"title": "Wind of Change", "artist": "The Scorpions", "page": 264},
    {"title": "Wish You Were Here", "artist": "Pink Floyd", "page": 265},
    {"title": "With a Little Help from My Friends", "artist": "The Beatles", "page": 266},
    {"title": "Wonderwall", "artist": "Oasis", "page": 267},
    {"title": "Word up", "artist": "Cameo", "page": 268},
    {"title": "Yellow", "artist": "Coldplay", "page": 269},
    {"title": "YMCA", "artist": "The Village People", "page": 270},
    {"title": "You Are My Sunshine", "artist": "Jimmie Davis and Charles Mitchell", "page": 271},
    {"title": "You Know I'm No Good", "artist": "Amy Winehouse", "page": 272},
    {"title": "Your Song", "artist": "Elton John", "page": 273},
    {"title": "You're So Vain", "artist": "Carly Simon", "page": 274},
    {"title": "You're the One that I Want", "artist": "Grease", "page": 275},
    {"title": "You've Got the Love", "artist": "Florence and the Machine", "page": 276},
    {"title": "Zombie", "artist": "The Cranberries", "page": 277}
]