var songs = [
    {"title": "A Little Less Conversation", "artist": "Elvis Presley vs JXL", "page": 8},
    {"title": "A Little Respect", "artist": "Erasure", "page": 9},
    {"title": "Accidentally in Love", "artist": "Counting Crows", "page": 10},
    {"title": "Africa", "artist": "Toto", "page": 11},
    {"title": "Ain't No Mountain High Enough", "artist": "Marvin Gaye & Tammi Terrell", "page": 12},
    {"title": "All About That Bass (abridged)", "artist": "Meghan Trainor ", "page": 13},
    {"title": "All Night Long", "artist": "Lionel Richie", "page": 14},
    {"title": "All Star", "artist": "Smash Mouth", "page": 15},
    {"title": "All That She Wants", "artist": "Ace of Base ", "page": 16},
    {"title": "Alright", "artist": "Supergrass ", "page": 17},
    {"title": "Always Look on the Bright Side of Life", "artist": "Monty Python ", "page": 18},
    {"title": "Always on my Mind", "artist": "Pet Shop Boys", "page": 19},
    {"title": "(Is this the Way to) Amarillo", "artist": "Tony Christie ", "page": 20},
    {"title": "American Idiot", "artist": "Green Day", "page": 21},
    {"title": "Angels", "artist": "Robbie Williams", "page": 22},
    {"title": "Annie's Song", "artist": "John Denver", "page": 23},
    {"title": "Back for Good", "artist": "Take That", "page": 24},
    {"title": "Back in the USSR", "artist": "The Beatles ", "page": 25},
    {"title": "Back to Black", "artist": "Amy Winehouse", "page": 26},
    {"title": "Bad Moon Rising", "artist": "Creedence Clearwater Revival", "page": 27},
    {"title": "Bad Romance", "artist": "Lady Gaga", "page": 28},
    {"title": "Baker Street", "artist": "Gerry Rafferty", "page": 29},
    {"title": "The Bare Necessities", "artist": "Phil Harris and Bruce Reitherman", "page": 30},
    {"title": "Be My Baby", "artist": "The Ronettes ", "page": 31},
    {"title": "Big Yellow Taxi", "artist": "Joni Mitchell ", "page": 32},
    {"title": "Blame it on the Boogie (abridged)", "artist": "The Jacksons ", "page": 33},
    {"title": "Blaze of Glory", "artist": "Jon Bon Jovi ", "page": 34},
    {"title": "Blister in the Sun", "artist": "The Violent Femmes", "page": 35},
    {"title": "Blowin' in the Wind", "artist": "Bob Dylan ", "page": 36},
    {"title": "Blue Monday", "artist": "New Order", "page": 37},
    {"title": "Blue Moon", "artist": "Richard Rodgers and Lorenz Hart ", "page": 38},
    {"title": "Blue Suede Shoes", "artist": "Elvis Presley", "page": 39},
    {"title": "Bohemian Like You", "artist": "The Dandy Warhols ", "page": 40},
    {"title": "Born to be Wild", "artist": "Steppenwolf ", "page": 41},
    {"title": "Boulevard of Broken Dreams", "artist": "Green Day ", "page": 42},
    {"title": "Breakfast at Tiffany's", "artist": "Deep Blue Something ", "page": 43},
    {"title": "Brimful of Asha (abridged)", "artist": "Cornershop ", "page": 44},
    {"title": "Bring Me Sunshine", "artist": "Morecambe & Wise ", "page": 45},
    {"title": "Brown Eyed Girl", "artist": "Van Morrison ", "page": 46},
    {"title": "Buck Rogers", "artist": "Feeder", "page": 47},
    {"title": "Budapest", "artist": "George Ezra", "page": 48},
    {"title": "Build Me Up Buttercup", "artist": "The Foundations ", "page": 49},
    {"title": "California Dreaming", "artist": "The Mamas & the Papas ", "page": 50},
    {"title": "Californication", "artist": "Red Hot Chili Peppers", "page": 51},
    {"title": "Cannonball", "artist": "Damien Rice ", "page": 52},
    {"title": "Can't Get You Out of My Head", "artist": "Kylie Minogue", "page": 53},
    {"title": "Can't Stop (abridged)", "artist": "Red Hot Chili Peppers", "page": 54},
    {"title": "Can't Take My Eyes Off You", "artist": "Frankie Valli", "page": 55},
    {"title": "Cat's in the Cradle", "artist": "Ugly Kid Joe ", "page": 56},
    {"title": "The Cave", "artist": "Mumford & Sons", "page": 57},
    {"title": "Cecilia", "artist": "Simon and Garfunkel", "page": 58},
    {"title": "C'est la Vie", "artist": "B*Witched", "page": 59},
    {"title": "The Chain", "artist": "Fleetwood Mac", "page": 60},
    {"title": "Chelsea Dagger", "artist": "The Fratellis", "page": 61},
    {"title": "City of New Orleans", "artist": "Arlo Guthrie", "page": 62},
    {"title": "Closing Time", "artist": "Semisonic ", "page": 63},
    {"title": "Come on Eileen", "artist": "Dexy's Midnight Runners", "page": 64},
    {"title": "Common People (short version)", "artist": "Pulp", "page": 65},
    {"title": "Complicated", "artist": "Avril Lavigne ", "page": 66},
    {"title": "Country House", "artist": "Blur ", "page": 67},
    {"title": "Crazy", "artist": "Gnarls Barkley", "page": 68},
    {"title": "Creep", "artist": "Radiohead ", "page": 69},
    {"title": "Crocodile Rock (abridged)", "artist": "Elton John ", "page": 70},
    {"title": "Dancing in the Dark", "artist": "Bruce Springsteen", "page": 71},
    {"title": "Dancing Queen", "artist": "Abba", "page": 72},
    {"title": "Daydream", "artist": "The Lovin' Spoonful ", "page": 73},
    {"title": "Daydream Believer", "artist": "The Monkees ", "page": 74},
    {"title": "Dedicated Follower of Fashion", "artist": "The Kinks", "page": 75},
    {"title": "Delilah", "artist": "Tom Jones", "page": 76},
    {"title": "Dirty Old Town", "artist": "The Pogues ", "page": 77},
    {"title": "Disco 2000 (abridged)", "artist": "Pulp ", "page": 78},
    {"title": "Do You Love Me", "artist": "The Contours ", "page": 79},
    {"title": "(Sittin' on the) Dock of the Bay", "artist": "Otis Redding", "page": 80},
    {"title": "Dog Days Are Over", "artist": "Florence and the Machine", "page": 81},
    {"title": "Don't Leave Me This Way", "artist": "The Communards ", "page": 82},
    {"title": "Don't Look Back in Anger — Oasis ", "page": 83},
    {"title": "Don't Speak (abridged)", "artist": "No Doubt", "page": 84},
    {"title": "Don't Stop Believin'", "artist": "Journey", "page": 85},
    {"title": "Don't Stop Me Now", "artist": "Queen ", "page": 86},
    {"title": "Don't Worry, Be Happy", "artist": "Bobby McFerrin ", "page": 87},
    {"title": "Don't You Forget About Me", "artist": "Simple Minds", "page": 88},
    {"title": "Don't You Want Me", "artist": "The Human League ", "page": 89},
    {"title": "Down Under", "artist": "Men at Work ", "page": 90},
    {"title": "Dream a Little Dream of Me", "artist": "The Mamas & The Papas ", "page": 91},
    {"title": "Dreaming of You — The Coral", "page": 92},
    {"title": "Dreams", "artist": "Fleetwood Mac", "page": 93},
    {"title": "Echo Beach", "artist": "Martha and the Muffins", "page": 94},
    {"title": "Enjoy the Silence", "artist": "Depeche Mode", "page": 95},
    {"title": "Ever Fallen in Love", "artist": "Buzzcocks ", "page": 96},
    {"title": "Every Breath You Take", "artist": "The Police ", "page": 97},
    {"title": "Everybody Wants to Rule the World", "artist": "Tears for Fears", "page": 98},
    {"title": "Everything I Do", "artist": "Bryan Adams", "page": 99},
    {"title": "Eye of the Tiger", "artist": "Survivor ", "page": 100},
    {"title": "Faith", "artist": "George Michael", "page": 101},
    {"title": "Feel it Still", "artist": "Portugal. The Man", "page": 102},
    {"title": "Feeling Good", "artist": "Nina Simone", "page": 103},
    {"title": "The Final Countdown", "artist": "Europe ", "page": 104},
    {"title": "Finally", "artist": "CeCe Peniston ", "page": 105},
    {"title": "Firework", "artist": "Katy Perry", "page": 106},
    {"title": "Five Foot Two, Eyes of Blue", "artist": "Lewis, Young & Henderson ", "page": 107},
    {"title": "Flashdance… What a Feeling", "artist": "Irene Cara", "page": 108},
    {"title": "Folsom Prison Blues", "artist": "Johnny Cash", "page": 109},
    {"title": "Footloose", "artist": "Kenny Loggins", "page": 110},
    {"title": "Forget You/F**You", "artist": "Cee Lo Green ", "page": 111},
    {"title": "Free Bird", "artist": "Lynyrd Skynyrd", "page": 112},
    {"title": "Free Fallin'", "artist": "Tom Petty", "page": 113},
    {"title": "Friday I'm in Love", "artist": "The Cure ", "page": 114},
    {"title": "Get Lucky (abridged)", "artist": "Daft Punk", "page": 115},
    {"title": "Girls Just Want to Have Fun", "artist": "Cyndi Lauper", "page": 116},
    {"title": "Give it Up", "artist": "KC and the Sunshine Band", "page": 117},
    {"title": "Go Your Own Way", "artist": "Fleetwood Mac ", "page": 118},
    {"title": "Gold", "artist": "Spandau Ballet", "page": 119},
    {"title": "Good Riddance (Time of Your Life)", "artist": "Green Day ", "page": 120},
    {"title": "Half the World Away", "artist": "Oasis ", "page": 121},
    {"title": "Hallelujah (abridged)", "artist": "Leonard Cohen", "page": 122},
    {"title": "Hand In My Pocket", "artist": "Alanis Morissette ", "page": 123},
    {"title": "Happy Birthday (traditional)", "page": 124},
    {"title": "Happy Together", "artist": "The Turtles ", "page": 125},
    {"title": "Have You Ever Seen the Rain?", "artist": "Creedence Clearwater Revival", "page": 126},
    {"title": "Heaven", "artist": "Bryan Adams ", "page": 127},
    {"title": "Heaven is a Place on Earth", "artist": "Belinda Carlisle", "page": 128},
    {"title": "“Heroes”", "artist": "David Bowie", "page": 129},
    {"title": "Hey Jude", "artist": "The Beatles ", "page": 130},
    {"title": "Hey Ya", "artist": "OutKast ", "page": 131},
    {"title": "Hi Ho Silver Lining", "artist": "Jeff Beck", "page": 132},
    {"title": "(Your Love Keeps Liftin' Me) Higher and Higher", "artist": "Jackie Wilson", "page": 133},
    {"title": "Hit Me Baby One More Time", "artist": "Britney Spears", "page": 134},
    {"title": "Hit the Road", "artist": "Ray Charles ", "page": 135},
    {"title": "Ho Hey", "artist": "The Lumineers ", "page": 136},
    {"title": "Hold On", "artist": "Wilson Phillips", "page": 137},
    {"title": "Holding Out For a Hero", "artist": "Bonnie Tyler", "page": 138},
    {"title": "Home", "artist": "Edward Sharpe & The Magnetic Zeros", "page": 139},
    {"title": "Hot n Cold", "artist": "Katy Perry", "page": 140},
    {"title": "Hotel California", "artist": "The Eagles", "page": 141},
    {"title": "House of Fun", "artist": "Madness", "page": 142},
    {"title": "House of the Rising Sun (abridged)", "artist": "The Animals ", "page": 143},
    {"title": "Human", "artist": "Rag'n'Bone Man", "page": 144},
    {"title": "Hurt", "artist": "Johnny Cash ", "page": 145},
    {"title": "Hysteria", "artist": "Muse", "page": 146},
    {"title": "I Bet that You Look Good on the Dancefloor", "artist": "Arctic Monkeys", "page": 147},
    {"title": "I Can See Clearly Now", "artist": "Johnny Nash ", "page": 148},
    {"title": "I Can't Help Myself (Sugar Pie Honey Bunch)", "artist": "Four Tops", "page": 149},
    {"title": "I Get Around", "artist": "The Beach Boys", "page": 150},
    {"title": "I Knew You Were Trouble", "artist": "Taylor Swift", "page": 151},
    {"title": "I Only Want to Be With You", "artist": "Dusty Springfield", "page": 152},
    {"title": "I Predict a Riot", "artist": "Kaiser Chiefs ", "page": 153},
    {"title": "I Think We're Alone Now", "artist": "Tiffany ", "page": 154},
    {"title": "I Wanna Be Like You", "artist": "Louis Prima and Phil Harris", "page": 155},
    {"title": "I Wanna Dance with Somebody", "artist": "Whitney Houston", "page": 156},
    {"title": "I Want to Break Free", "artist": "Queen", "page": 157},
    {"title": "I Want to Know What Love Is", "artist": "Foreigner", "page": 158},
    {"title": "I Will Survive", "artist": "Gloria Gaynor ", "page": 159},
    {"title": "I'll Be There For You (Friends theme)", "artist": "The Rembrandts ", "page": 160},
    {"title": "I'll Be Your Baby Tonight", "artist": "Bob Dylan ", "page": 161},
    {"title": "I'll Fly Away", "artist": "Alison Krauss and Gillian Welch ", "page": 162},
    {"title": "I'm a Believer", "artist": "The Monkees ", "page": 163},
    {"title": "I'm Gonna Be (500 Miles)", "artist": "The Proclaimers ", "page": 164},
    {"title": "I'm Still Standing", "artist": "Elton John", "page": 165},
    {"title": "I'm into Something Good", "artist": "Herman's Hermits", "page": 166},
    {"title": "I'm Yours", "artist": "Jason Mraz ", "page": 167},
    {"title": "Iko Iko", "artist": "James Crawford", "page": 168},
    {"title": "Imagine", "artist": "John Lennon ", "page": 169},
    {"title": "In the Air Tonight", "artist": "Phil Collins", "page": 170},
    {"title": "Iris", "artist": "The Goo Goo Dolls", "page": 171},
    {"title": "Ironic", "artist": "Alanis Morisette", "page": 172},
    {"title": "It Must Be Love", "artist": "Madness ", "page": 173},
    {"title": "It's Not Unusual", "artist": "Tom Jones", "page": 174},
    {"title": "Jamming", "artist": "Bob Marley ", "page": 175},
    {"title": "Johnny B. Goode", "artist": "Chuck Berry ", "page": 176},
    {"title": "Jolene", "artist": "Dolly Parton ", "page": 177},
    {"title": "Just Can't Get Enough", "artist": "Depeche Mode", "page": 178},
    {"title": "Karma Chameleon", "artist": "Culture Club ", "page": 179},
    {"title": "Keep the Faith", "artist": "Bon Jovi ", "page": 180},
    {"title": "Kids", "artist": "MGMT", "page": 181},
    {"title": "Kids in America", "artist": "Kim Wilde ", "page": 182},
    {"title": "Killing Me Softly with his Song", "artist": "Roberta Flack", "page": 183},
    {"title": "King of the Road", "artist": "Roger Miller ", "page": 184},
    {"title": "Kiss Me", "artist": "Sixpence None the Richer", "page": 185},
    {"title": "Knockin' On Heaven's Door", "artist": "Bob Dylan", "page": 186},
    {"title": "Lady Madonna", "artist": "The Beatles", "page": 187},
    {"title": "Last Nite", "artist": "The Strokes", "page": 188},
    {"title": "Learn to Fly", "artist": "Foo Fighters", "page": 189},
    {"title": "Let it Be (abridged)", "artist": "The Beatles", "page": 190},
    {"title": "Let it Go", "artist": "Idina Menzel", "page": 191},
    {"title": "The Letter", "artist": "The Box Tops ", "page": 192},
    {"title": "Like a Prayer", "artist": "Madonna ", "page": 193},
    {"title": "The Lion Sleeps Tonight", "artist": "The Tokens", "page": 194},
    {"title": "Little Lion Man", "artist": "Mumford & Sons", "page": 195},
    {"title": "Little Talks", "artist": "Of Monsters and Men", "page": 196},
    {"title": "Live Forever", "artist": "Oasis ", "page": 197},
    {"title": "Livin' la Vida Loca", "artist": "Ricky Martin", "page": 198},
    {"title": "Livin' on a Prayer", "artist": "Bon Jovi ", "page": 199},
    {"title": "The Loco-motion", "artist": "Little Eva", "page": 200},
    {"title": "Lola", "artist": "The Kinks ", "page": 201},
    {"title": "Losing My Religion", "artist": "REM ", "page": 202},
    {"title": "Love Shack", "artist": "The B-52s", "page": 203},
    {"title": "Love Will Tear Us Apart", "artist": "Joy Division", "page": 204},
    {"title": "Lucky Man", "artist": "The Verve ", "page": 205},
    {"title": "Mad World", "artist": "Gary Jules", "page": 206},
    {"title": "Maggie May", "artist": "Rod Stewart ", "page": 207},
    {"title": "Make Me Smile (Come Up and See Me)", "artist": "Steve Harley", "page": 208},
    {"title": "Mamma Mia", "artist": "ABBA", "page": 209},
    {"title": "The Man Who Sold the World", "artist": "David Bowie", "page": 210},
    {"title": "Man! I Feel Like a Woman!", "artist": "Shania Twain", "page": 211},
    {"title": "Man of Constant Sorrow", "artist": "The Soggy Bottom Boys", "page": 212},
    {"title": "Maybe Tomorrow", "artist": "Terry Bush (Littlest Hobo theme) ", "page": 213},
    {"title": "Me and Julio Down by the Schoolyard", "artist": "Paul Simon ", "page": 214},
    {"title": "Minnie the Moocher", "artist": "Cab Calloway", "page": 215},
    {"title": "Monkey Man", "artist": "Toots and the Maytals", "page": 216},
    {"title": "Moondance", "artist": "Van Morrison ", "page": 217},
    {"title": "More Than Words", "artist": "Extreme", "page": 218},
    {"title": "Movin' On Up", "artist": "Primal Scream", "page": 219},
    {"title": "Mr Blue Sky (abridged)", "artist": "Electric Light Orchestra", "page": 220},
    {"title": "Mr Brightside", "artist": "The Killers ", "page": 221},
    {"title": "Mrs Robinson", "artist": "Simon & Garfunkel ", "page": 222},
    {"title": "My Favourite Game", "artist": "The Cardigans ", "page": 223},
    {"title": "Mysterious Girl (abridged)", "artist": "Peter Andre", "page": 224},
    {"title": "Never Ever", "artist": "All Saints", "page": 225},
    {"title": "New York, New York", "artist": "Frank Sinatra ", "page": 226},
    {"title": "Nine to Five", "artist": "Dolly Parton ", "page": 227},
    {"title": "No Surprises", "artist": "Radiohead", "page": 228},
    {"title": "No Woman, No Cry", "artist": "Bob Marley & The Wailers", "page": 229},
    {"title": "Octopus's Garden", "artist": "The Beatles ", "page": 230},
    {"title": "Oh, Pretty Woman", "artist": "Roy Orbison ", "page": 231},
    {"title": "The One and Only", "artist": "Chesney Hawkes", "page": 232},
    {"title": "One Day Like This", "artist": "Elbow", "page": 233},
    {"title": "Otherside", "artist": "Red Hot Chili Peppers", "page": 234},
    {"title": "(Lookin' Back) Over My Shoulder", "artist": "Mike + the Mechanics", "page": 235},
    {"title": "Paint it Black", "artist": "The Rolling Stones ", "page": 236},
    {"title": "Paradise", "artist": "George Ezra", "page": 237},
    {"title": "Paradise City (abridged)", "artist": "Guns 'N Roses", "page": 238},
    {"title": "The Passenger (abridged)", "artist": "Iggy Pop", "page": 239},
    {"title": "Perfect Day", "artist": "Lou Reed ", "page": 240},
    {"title": "Piano Man (abridged)", "artist": "Billy Joel", "page": 241},
    {"title": "Piece of my Heart", "artist": "Erma Franklin ", "page": 242},
    {"title": "Pinball Wizard", "artist": "The Who ", "page": 243},
    {"title": "Poison", "artist": "Alice Cooper", "page": 244},
    {"title": "Price Tag (abridged)", "artist": "Jessie J ", "page": 245},
    {"title": "Proud Mary", "artist": "Tina Turner", "page": 246},
    {"title": "Psycho Killer", "artist": "Talking Heads ", "page": 247},
    {"title": "Pumped Up Kicks", "artist": "Foster the People", "page": 248},
    {"title": "Que Sera Sera", "artist": "Doris Day ", "page": 249},
    {"title": "Raindrops Keep Fallin' on my Head", "artist": "B J Thomas ", "page": 250},
    {"title": "Rasputin (abridged)", "artist": "Boney M", "page": 251},
    {"title": "Ring of Fire", "artist": "Johnny Cash", "page": 252},
    {"title": "Riptide", "artist": "Vance Joy", "page": 253},
    {"title": "Rocket Man", "artist": "Elton John ", "page": 254},
    {"title": "Rolling in the Deep", "artist": "Adele ", "page": 255},
    {"title": "Ruby", "artist": "Kaiser Chiefs", "page": 256},
    {"title": "Runaround Sue", "artist": "Dion", "page": 257},
    {"title": "Runaway", "artist": "Del Shannon", "page": 258},
    {"title": "Sail Away", "artist": "David Gray", "page": 259},
    {"title": "Save Tonight", "artist": "Eagle Eye Cherry", "page": 260},
    {"title": "Shake it Off", "artist": "Taylor Swift", "page": 261},
    {"title": "Shotgun", "artist": "George Ezra", "page": 262},
    {"title": "Should I Stay or Should I Go", "artist": "The Clash ", "page": 263},
    {"title": "Simply the Best", "artist": "Tina Turner", "page": 264},
    {"title": "Sit Down", "artist": "James", "page": 265},
    {"title": "Skinny Love", "artist": "Bon Iver ", "page": 266},
    {"title": "Sloop John B", "artist": "The Beach Boys ", "page": 267},
    {"title": "Somebody That I Used to Know", "artist": "Gotye", "page": 268},
    {"title": "Somewhere Only We Know", "artist": "Keane", "page": 269},
    {"title": "Somewhere Over the Rainbow / Wonderful World", "artist": "Israel Kamakawiwo'ole ", "page": 270},
    {"title": "SOS", "artist": "Abba", "page": 271},
    {"title": "Sound of Silence", "artist": "Simon & Garfunkel ", "page": 272},
    {"title": "Space Oddity", "artist": "David Bowie ", "page": 273},
    {"title": "Spirit in the Sky", "artist": "Norman Greenbaum ", "page": 274},
    {"title": "Stand by Me", "artist": "Ben E King ", "page": 275},
    {"title": "Starlight", "artist": "Muse", "page": 276},
    {"title": "Starman", "artist": "David Bowie", "page": 277},
    {"title": "Stuck in the Middle with You", "artist": "Stealers Wheel", "page": 278},
    {"title": "Summer of 69", "artist": "Bryan Adams", "page": 279},
    {"title": "Sunny Afternoon", "artist": "The Kinks ", "page": 280},
    {"title": "Suspicious Minds (abridged)", "artist": "Elvis Presley ", "page": 281},
    {"title": "Sway", "artist": "Dean Martin", "page": 282},
    {"title": "Sweet Caroline", "artist": "Neil Diamond", "page": 283},
    {"title": "Sweet Child o' Mine", "artist": "Guns N' Roses", "page": 284},
    {"title": "Sweet Dreams", "artist": "Eurythmics", "page": 285},
    {"title": "Sweet Home Alabama", "artist": "Lynyrd Skynyrd ", "page": 286},
    {"title": "Tainted Love", "artist": "Soft Cell", "page": 287},
    {"title": "Take it Easy", "artist": "The Eagles ", "page": 288},
    {"title": "Take Me Home, Country Roads", "artist": "John Denver ", "page": 289},
    {"title": "Take Me Out", "artist": "Franz Ferdinand", "page": 290},
    {"title": "Take on Me", "artist": "Aha", "page": 291},
    {"title": "Take Your Mama", "artist": "Scissor Sisters ", "page": 292},
    {"title": "Teenage Dirtbag", "artist": "Wheatus ", "page": 293},
    {"title": "Teenage Kicks", "artist": "The Undertones ", "page": 294},
    {"title": "Tell Me Ma", "artist": "The Dubliners ", "page": 295},
    {"title": "That Don't Impress Me Much", "artist": "Shania Twain", "page": 296},
    {"title": "There is a Light that Never Goes Out", "artist": "The Smiths", "page": 297},
    {"title": "There She Goes", "artist": "The La's", "page": 298},
    {"title": "These Boots Are Made for Walkin'", "artist": "Nancy Sinatra", "page": 299},
    {"title": "Thorn in my Side", "artist": "Eurythmics", "page": 300},
    {"title": "Three Little Birds", "artist": "Bob Marley", "page": 301},
    {"title": "Time After Time", "artist": "Cindy Lauper ", "page": 302},
    {"title": "Titanium", "artist": "David Guetta ft. Sia", "page": 303},
    {"title": "Torn", "artist": "Natalie Imbruglia", "page": 304},
    {"title": "Total Eclipse of the Heart (abridged)", "artist": "Bonnie Tyler", "page": 305},
    {"title": "Toxic", "artist": "Britney Spears ", "page": 306},
    {"title": "True Colours (abridged)", "artist": "Cindy Lauper ", "page": 307},
    {"title": "True Faith", "artist": "New Order ", "page": 308},
    {"title": "Tubthumping", "artist": "Chumbawumba ", "page": 309},
    {"title": "Two Princes", "artist": "Spin Doctors", "page": 310},
    {"title": "Umbrella", "artist": "Rihanna ", "page": 311},
    {"title": "Under The Boardwalk", "artist": "The Drifters", "page": 312},
    {"title": "Under the Bridge", "artist": "Red Hot Chili Peppers ", "page": 313},
    {"title": "Valerie", "artist": "Amy Winehouse", "page": 314},
    {"title": "Video Killed the Radio Star", "artist": "The Buggles", "page": 315},
    {"title": "Waiting for a Star to Fall", "artist": "Boy Meets Girl", "page": 316},
    {"title": "Wake Me Up Before You Go-Go", "artist": "Wham!", "page": 317},
    {"title": "Wake up Boo", "artist": "Boo Radleys", "page": 318},
    {"title": "Walk of Life", "artist": "Dire Straits ", "page": 319},
    {"title": "Walking in Memphis", "artist": "Mark Cohn ", "page": 320},
    {"title": "Walking on Sunshine", "artist": "Katrina and the Waves", "page": 321},
    {"title": "Wannabe", "artist": "The Spice Girls", "page": 322},
    {"title": "Wanted: Dead or Alive", "artist": "Bon Jovi", "page": 323},
    {"title": "Waterfalls", "artist": "TLC", "page": 324},
    {"title": "The Way It Is", "artist": "Bruce Hornsby", "page": 325},
    {"title": "We Are Family", "artist": "Sister Sledge ", "page": 326},
    {"title": "We Are Young", "artist": "Fun with Janelle Monae", "page": 327},
    {"title": "We Built this City", "artist": "Starship ", "page": 328},
    {"title": "Weather with You", "artist": "Crowded House", "page": 329},
    {"title": "What's Up?", "artist": "4 Non Blondes ", "page": 330},
    {"title": "When the Going Gets Tough", "artist": "Billy Ocean", "page": 331},
    {"title": "When You Were Young", "artist": "The Killers", "page": 332},
    {"title": "Where Do You Go to My Lovely? (abridged)", "artist": "Peter Sarstedt", "page": 333},
    {"title": "White Wedding", "artist": "Billy Idol", "page": 334},
    {"title": "Why Does it Always Rain on Me?", "artist": "Travis ", "page": 335},
    {"title": "Wichita Lineman", "artist": "Glen Campbell", "page": 336},
    {"title": "Wicked Game", "artist": "Chris Isaak ", "page": 337},
    {"title": "Wild World", "artist": "Cat Stevens", "page": 338},
    {"title": "Will You Still Love me Tomorrow?", "artist": "The Shirelles ", "page": 339},
    {"title": "Wind of Change", "artist": "The Scorpions ", "page": 340},
    {"title": "Wish You Were Here", "artist": "Pink Floyd ", "page": 341},
    {"title": "With a Little Help from my Friends", "artist": "The Beatles", "page": 342},
    {"title": "Wonderful World", "artist": "Sam Cooke ", "page": 343},
    {"title": "Wonderwall", "artist": "Oasis ", "page": 344},
    {"title": "Word up", "artist": "Cameo", "page": 345},
    {"title": "Yellow", "artist": "Coldplay ", "page": 346},
    {"title": "YMCA", "artist": "The Village People", "page": 347},
    {"title": "You Are My Sunshine", "artist": "The Pine Ridge Boys", "page": 348},
    {"title": "You Know I'm No Good", "artist": "Amy Winehouse ", "page": 349},
    {"title": "You Make My Dreams", "artist": "Hall & Oates", "page": 350},
    {"title": "You've Got the Love", "artist": "Florence and the Machine ", "page": 351},
    {"title": "Your Song", "artist": "Elton John ", "page": 352},
    {"title": "You're So Vain", "artist": "Carly Simon", "page": 353},
    {"title": "You're the One that I Want", "artist": "Grease", "page": 354},
    {"title": "Zombie", "artist": "The Cranberries ", "page": 355}
]